/********************************************************************************
** Form generated from reading UI file 'widget.ui'
**
** Created by: Qt User Interface Compiler version 5.15.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_WIDGET_H
#define UI_WIDGET_H

#include <QtCore/QVariant>
#include <QtGui/QIcon>
#include <QtWidgets/QApplication>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QLCDNumber>
#include <QtWidgets/QLabel>
#include <QtWidgets/QListWidget>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSlider>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_Widget
{
public:
    QListWidget *listWidget_ImageList;
    QPushButton *pushButton_ChooseFolder;
    QGroupBox *groupBox_OriImg;
    QLabel *label_OriImg;
    QLabel *label_ImageList;
    QGroupBox *groupBox_OriImgF;
    QTabWidget *tabWidget_OriImgF;
    QWidget *tab_OriImgF_S;
    QLabel *label_OriImgF_S;
    QWidget *tab_OriImgF_PA;
    QLabel *label_OriImgF_PA;
    QGroupBox *groupBox_ProImg;
    QLabel *label_ProImg;
    QPushButton *pushButton_ProImg_store;
    QGroupBox *groupBox_ProImgF;
    QTabWidget *tabWidget_ProImgF;
    QWidget *tab_ProImgF_S;
    QLabel *label_ProImgF_S;
    QWidget *tab_ProImgF_PA;
    QLabel *label_ProImgF_PA;
    QGroupBox *groupBox_Func;
    QTabWidget *tabWidget_Func;
    QWidget *tab;
    QPushButton *pushButton_IF;
    QPushButton *pushButton_ADDN;
    QWidget *tab_Func_LP;
    QTabWidget *tabWidget_Func_LP;
    QWidget *tab_Func_LP_ID;
    QGroupBox *groupBox_Func_LP_ID_D0;
    QSlider *horizontalSlider_Func_LP_ID_D0;
    QLCDNumber *lcdNumber_Func_LP_ID_D0;
    QWidget *tab_Func_LP_Bu;
    QGroupBox *groupBox_Func_LP_Bu_D0;
    QSlider *horizontalSlider_Func_LP_Bu_D0;
    QLCDNumber *lcdNumber_Func_LP_Bu_D0;
    QGroupBox *groupBox_Func_LP_Bu_N;
    QSlider *horizontalSlider_Func_LP_Bu_N;
    QLCDNumber *lcdNumber_Func_LP_Bu_N;
    QWidget *tab_Func_LP_Ga;
    QGroupBox *groupBox_Func_LP_Ga_D0;
    QSlider *horizontalSlider_Func_LP_Ga_D0;
    QLCDNumber *lcdNumber_Func_LP_Ga_D0;
    QWidget *tab_Func_HP;
    QTabWidget *tabWidget_Func_HP;
    QWidget *tab_Func_HP_ID;
    QGroupBox *groupBox_Func_HP_ID_D0;
    QSlider *horizontalSlider_Func_HP_ID_D0;
    QLCDNumber *lcdNumber_Func_HP_ID_D0;
    QWidget *tab_Func_HP_Bu;
    QGroupBox *groupBox_Func_HP_Bu_D0;
    QSlider *horizontalSlider_Func_HP_Bu_D0;
    QLCDNumber *lcdNumber_Func_HP_Bu_D0;
    QGroupBox *groupBox_Func_HP_Bu_N;
    QSlider *horizontalSlider_Func_HP_Bu_N;
    QLCDNumber *lcdNumber_Func_HP_Bu_N;
    QWidget *tab_Func_HP_Ga;
    QGroupBox *groupBox_Func_HP_Ga_D0;
    QSlider *horizontalSlider_Func_HP_Ga_D0;
    QLCDNumber *lcdNumber_Func_HP_Ga_D0;
    QWidget *tab_Func_Homo;
    QGroupBox *groupBox_Func_Homo_RH;
    QSlider *horizontalSlider_Func_Homo_RH;
    QLCDNumber *lcdNumber_Func_Homo_RH;
    QGroupBox *groupBox_Func_Homo_RL;
    QSlider *horizontalSlider_Func_Homo_RL;
    QLCDNumber *lcdNumber_Func_Homo_RL;
    QGroupBox *groupBox_Func_Homo_C;
    QSlider *horizontalSlider_Func_Homo_C;
    QLCDNumber *lcdNumber_Func_Homo_C;
    QGroupBox *groupBox_Func_Homo_D0;
    QSlider *horizontalSlider_Func_Homo_D0;
    QLCDNumber *lcdNumber_Func_Homo_D0;
    QWidget *tab_Func_CreMBImg;
    QGroupBox *groupBox_Func_CreMBImg_A;
    QSlider *horizontalSlider_Func_CreMBImg_A;
    QLCDNumber *lcdNumber_Func_CreMBImg_A;
    QGroupBox *groupBox_Func_CreMBImg_B;
    QSlider *horizontalSlider_Func_CreMBImg_B;
    QLCDNumber *lcdNumber_Func_CreMBImg_B;
    QWidget *tab_Func_RemMBImg;
    QTabWidget *tabWidget_Func_RemMBImg;
    QWidget *tab_Func_RemMBImg_IF;
    QGroupBox *groupBox_Func_RemMBImg_IF_A;
    QSlider *horizontalSlider_Func_RemMBImg_IF_A;
    QLCDNumber *lcdNumber_Func_RemMBImg_IF_A;
    QGroupBox *groupBox_Func_RemMBImg_IF_B;
    QSlider *horizontalSlider_Func_RemMBImg_IF_B;
    QLCDNumber *lcdNumber_Func_RemMBImg_IF_B;
    QWidget *tab_Func_RemMBImg_WF;
    QGroupBox *groupBox_Func_RemMBImg_WF_A;
    QSlider *horizontalSlider_Func_RemMBImg_WF_A;
    QLCDNumber *lcdNumber_Func_RemMBImg_WF_A;
    QGroupBox *groupBox_Func_RemMBImg_WF_B;
    QSlider *horizontalSlider_Func_RemMBImg_WF_B;
    QLCDNumber *lcdNumber_Func_RemMBImg_WF_B;
    QGroupBox *groupBox_Func_RemMBImg_WF_K;
    QSlider *horizontalSlider_Func_RemMBImg_WF_K;
    QLCDNumber *lcdNumber_Func_RemMBImg_WF_K;
    QPushButton *pushButton_Execute;
    QPushButton *pushButton_Clear;

    void setupUi(QWidget *Widget)
    {
        if (Widget->objectName().isEmpty())
            Widget->setObjectName(QString::fromUtf8("Widget"));
        Widget->resize(1206, 963);
        Widget->setAutoFillBackground(false);
        listWidget_ImageList = new QListWidget(Widget);
        listWidget_ImageList->setObjectName(QString::fromUtf8("listWidget_ImageList"));
        listWidget_ImageList->setGeometry(QRect(10, 80, 371, 381));
        pushButton_ChooseFolder = new QPushButton(Widget);
        pushButton_ChooseFolder->setObjectName(QString::fromUtf8("pushButton_ChooseFolder"));
        pushButton_ChooseFolder->setGeometry(QRect(10, 20, 220, 30));
        groupBox_OriImg = new QGroupBox(Widget);
        groupBox_OriImg->setObjectName(QString::fromUtf8("groupBox_OriImg"));
        groupBox_OriImg->setGeometry(QRect(400, 30, 380, 431));
        label_OriImg = new QLabel(groupBox_OriImg);
        label_OriImg->setObjectName(QString::fromUtf8("label_OriImg"));
        label_OriImg->setGeometry(QRect(30, 80, 320, 320));
        label_ImageList = new QLabel(Widget);
        label_ImageList->setObjectName(QString::fromUtf8("label_ImageList"));
        label_ImageList->setGeometry(QRect(10, 60, 220, 20));
        groupBox_OriImgF = new QGroupBox(Widget);
        groupBox_OriImgF->setObjectName(QString::fromUtf8("groupBox_OriImgF"));
        groupBox_OriImgF->setGeometry(QRect(790, 30, 380, 431));
        tabWidget_OriImgF = new QTabWidget(groupBox_OriImgF);
        tabWidget_OriImgF->setObjectName(QString::fromUtf8("tabWidget_OriImgF"));
        tabWidget_OriImgF->setGeometry(QRect(10, 30, 361, 391));
        tab_OriImgF_S = new QWidget();
        tab_OriImgF_S->setObjectName(QString::fromUtf8("tab_OriImgF_S"));
        label_OriImgF_S = new QLabel(tab_OriImgF_S);
        label_OriImgF_S->setObjectName(QString::fromUtf8("label_OriImgF_S"));
        label_OriImgF_S->setGeometry(QRect(20, 20, 320, 320));
        tabWidget_OriImgF->addTab(tab_OriImgF_S, QString());
        tab_OriImgF_PA = new QWidget();
        tab_OriImgF_PA->setObjectName(QString::fromUtf8("tab_OriImgF_PA"));
        label_OriImgF_PA = new QLabel(tab_OriImgF_PA);
        label_OriImgF_PA->setObjectName(QString::fromUtf8("label_OriImgF_PA"));
        label_OriImgF_PA->setGeometry(QRect(20, 20, 320, 320));
        tabWidget_OriImgF->addTab(tab_OriImgF_PA, QString());
        groupBox_ProImg = new QGroupBox(Widget);
        groupBox_ProImg->setObjectName(QString::fromUtf8("groupBox_ProImg"));
        groupBox_ProImg->setGeometry(QRect(400, 470, 380, 431));
        label_ProImg = new QLabel(groupBox_ProImg);
        label_ProImg->setObjectName(QString::fromUtf8("label_ProImg"));
        label_ProImg->setGeometry(QRect(30, 80, 320, 320));
        pushButton_ProImg_store = new QPushButton(groupBox_ProImg);
        pushButton_ProImg_store->setObjectName(QString::fromUtf8("pushButton_ProImg_store"));
        pushButton_ProImg_store->setGeometry(QRect(10, 30, 40, 40));
        QIcon icon;
        icon.addFile(QString::fromUtf8("../img/storage.png"), QSize(), QIcon::Normal, QIcon::Off);
        pushButton_ProImg_store->setIcon(icon);
        pushButton_ProImg_store->setIconSize(QSize(50, 50));
        groupBox_ProImgF = new QGroupBox(Widget);
        groupBox_ProImgF->setObjectName(QString::fromUtf8("groupBox_ProImgF"));
        groupBox_ProImgF->setGeometry(QRect(790, 470, 380, 431));
        tabWidget_ProImgF = new QTabWidget(groupBox_ProImgF);
        tabWidget_ProImgF->setObjectName(QString::fromUtf8("tabWidget_ProImgF"));
        tabWidget_ProImgF->setGeometry(QRect(10, 30, 361, 391));
        tab_ProImgF_S = new QWidget();
        tab_ProImgF_S->setObjectName(QString::fromUtf8("tab_ProImgF_S"));
        label_ProImgF_S = new QLabel(tab_ProImgF_S);
        label_ProImgF_S->setObjectName(QString::fromUtf8("label_ProImgF_S"));
        label_ProImgF_S->setGeometry(QRect(20, 20, 320, 320));
        tabWidget_ProImgF->addTab(tab_ProImgF_S, QString());
        tab_ProImgF_PA = new QWidget();
        tab_ProImgF_PA->setObjectName(QString::fromUtf8("tab_ProImgF_PA"));
        label_ProImgF_PA = new QLabel(tab_ProImgF_PA);
        label_ProImgF_PA->setObjectName(QString::fromUtf8("label_ProImgF_PA"));
        label_ProImgF_PA->setGeometry(QRect(20, 20, 320, 320));
        tabWidget_ProImgF->addTab(tab_ProImgF_PA, QString());
        groupBox_Func = new QGroupBox(Widget);
        groupBox_Func->setObjectName(QString::fromUtf8("groupBox_Func"));
        groupBox_Func->setGeometry(QRect(10, 470, 370, 430));
        tabWidget_Func = new QTabWidget(groupBox_Func);
        tabWidget_Func->setObjectName(QString::fromUtf8("tabWidget_Func"));
        tabWidget_Func->setGeometry(QRect(10, 30, 350, 355));
        tab = new QWidget();
        tab->setObjectName(QString::fromUtf8("tab"));
        pushButton_IF = new QPushButton(tab);
        pushButton_IF->setObjectName(QString::fromUtf8("pushButton_IF"));
        pushButton_IF->setGeometry(QRect(20, 24, 311, 31));
        pushButton_ADDN = new QPushButton(tab);
        pushButton_ADDN->setObjectName(QString::fromUtf8("pushButton_ADDN"));
        pushButton_ADDN->setGeometry(QRect(20, 60, 311, 31));
        tabWidget_Func->addTab(tab, QString());
        tab_Func_LP = new QWidget();
        tab_Func_LP->setObjectName(QString::fromUtf8("tab_Func_LP"));
        tabWidget_Func_LP = new QTabWidget(tab_Func_LP);
        tabWidget_Func_LP->setObjectName(QString::fromUtf8("tabWidget_Func_LP"));
        tabWidget_Func_LP->setGeometry(QRect(10, 10, 325, 300));
        tab_Func_LP_ID = new QWidget();
        tab_Func_LP_ID->setObjectName(QString::fromUtf8("tab_Func_LP_ID"));
        groupBox_Func_LP_ID_D0 = new QGroupBox(tab_Func_LP_ID);
        groupBox_Func_LP_ID_D0->setObjectName(QString::fromUtf8("groupBox_Func_LP_ID_D0"));
        groupBox_Func_LP_ID_D0->setGeometry(QRect(10, 10, 300, 111));
        QFont font;
        font.setPointSize(12);
        font.setBold(true);
        font.setWeight(75);
        groupBox_Func_LP_ID_D0->setFont(font);
        horizontalSlider_Func_LP_ID_D0 = new QSlider(groupBox_Func_LP_ID_D0);
        horizontalSlider_Func_LP_ID_D0->setObjectName(QString::fromUtf8("horizontalSlider_Func_LP_ID_D0"));
        horizontalSlider_Func_LP_ID_D0->setGeometry(QRect(10, 30, 280, 50));
        horizontalSlider_Func_LP_ID_D0->setMinimum(1);
        horizontalSlider_Func_LP_ID_D0->setMaximum(500);
        horizontalSlider_Func_LP_ID_D0->setOrientation(Qt::Horizontal);
        lcdNumber_Func_LP_ID_D0 = new QLCDNumber(groupBox_Func_LP_ID_D0);
        lcdNumber_Func_LP_ID_D0->setObjectName(QString::fromUtf8("lcdNumber_Func_LP_ID_D0"));
        lcdNumber_Func_LP_ID_D0->setGeometry(QRect(230, 70, 60, 30));
        lcdNumber_Func_LP_ID_D0->setDigitCount(3);
        lcdNumber_Func_LP_ID_D0->setProperty("value", QVariant(1.000000000000000));
        tabWidget_Func_LP->addTab(tab_Func_LP_ID, QString());
        tab_Func_LP_Bu = new QWidget();
        tab_Func_LP_Bu->setObjectName(QString::fromUtf8("tab_Func_LP_Bu"));
        groupBox_Func_LP_Bu_D0 = new QGroupBox(tab_Func_LP_Bu);
        groupBox_Func_LP_Bu_D0->setObjectName(QString::fromUtf8("groupBox_Func_LP_Bu_D0"));
        groupBox_Func_LP_Bu_D0->setGeometry(QRect(10, 10, 300, 111));
        groupBox_Func_LP_Bu_D0->setFont(font);
        horizontalSlider_Func_LP_Bu_D0 = new QSlider(groupBox_Func_LP_Bu_D0);
        horizontalSlider_Func_LP_Bu_D0->setObjectName(QString::fromUtf8("horizontalSlider_Func_LP_Bu_D0"));
        horizontalSlider_Func_LP_Bu_D0->setGeometry(QRect(10, 30, 280, 50));
        horizontalSlider_Func_LP_Bu_D0->setMinimum(1);
        horizontalSlider_Func_LP_Bu_D0->setMaximum(500);
        horizontalSlider_Func_LP_Bu_D0->setOrientation(Qt::Horizontal);
        lcdNumber_Func_LP_Bu_D0 = new QLCDNumber(groupBox_Func_LP_Bu_D0);
        lcdNumber_Func_LP_Bu_D0->setObjectName(QString::fromUtf8("lcdNumber_Func_LP_Bu_D0"));
        lcdNumber_Func_LP_Bu_D0->setGeometry(QRect(230, 70, 60, 30));
        lcdNumber_Func_LP_Bu_D0->setDigitCount(3);
        lcdNumber_Func_LP_Bu_D0->setProperty("value", QVariant(1.000000000000000));
        groupBox_Func_LP_Bu_N = new QGroupBox(tab_Func_LP_Bu);
        groupBox_Func_LP_Bu_N->setObjectName(QString::fromUtf8("groupBox_Func_LP_Bu_N"));
        groupBox_Func_LP_Bu_N->setGeometry(QRect(10, 140, 300, 111));
        groupBox_Func_LP_Bu_N->setFont(font);
        horizontalSlider_Func_LP_Bu_N = new QSlider(groupBox_Func_LP_Bu_N);
        horizontalSlider_Func_LP_Bu_N->setObjectName(QString::fromUtf8("horizontalSlider_Func_LP_Bu_N"));
        horizontalSlider_Func_LP_Bu_N->setGeometry(QRect(10, 30, 280, 50));
        horizontalSlider_Func_LP_Bu_N->setMinimum(1);
        horizontalSlider_Func_LP_Bu_N->setMaximum(20);
        horizontalSlider_Func_LP_Bu_N->setOrientation(Qt::Horizontal);
        lcdNumber_Func_LP_Bu_N = new QLCDNumber(groupBox_Func_LP_Bu_N);
        lcdNumber_Func_LP_Bu_N->setObjectName(QString::fromUtf8("lcdNumber_Func_LP_Bu_N"));
        lcdNumber_Func_LP_Bu_N->setGeometry(QRect(230, 70, 60, 30));
        lcdNumber_Func_LP_Bu_N->setDigitCount(3);
        lcdNumber_Func_LP_Bu_N->setProperty("value", QVariant(1.000000000000000));
        tabWidget_Func_LP->addTab(tab_Func_LP_Bu, QString());
        tab_Func_LP_Ga = new QWidget();
        tab_Func_LP_Ga->setObjectName(QString::fromUtf8("tab_Func_LP_Ga"));
        groupBox_Func_LP_Ga_D0 = new QGroupBox(tab_Func_LP_Ga);
        groupBox_Func_LP_Ga_D0->setObjectName(QString::fromUtf8("groupBox_Func_LP_Ga_D0"));
        groupBox_Func_LP_Ga_D0->setGeometry(QRect(10, 10, 300, 111));
        groupBox_Func_LP_Ga_D0->setFont(font);
        horizontalSlider_Func_LP_Ga_D0 = new QSlider(groupBox_Func_LP_Ga_D0);
        horizontalSlider_Func_LP_Ga_D0->setObjectName(QString::fromUtf8("horizontalSlider_Func_LP_Ga_D0"));
        horizontalSlider_Func_LP_Ga_D0->setGeometry(QRect(10, 30, 280, 50));
        horizontalSlider_Func_LP_Ga_D0->setMinimum(1);
        horizontalSlider_Func_LP_Ga_D0->setMaximum(500);
        horizontalSlider_Func_LP_Ga_D0->setOrientation(Qt::Horizontal);
        lcdNumber_Func_LP_Ga_D0 = new QLCDNumber(groupBox_Func_LP_Ga_D0);
        lcdNumber_Func_LP_Ga_D0->setObjectName(QString::fromUtf8("lcdNumber_Func_LP_Ga_D0"));
        lcdNumber_Func_LP_Ga_D0->setGeometry(QRect(230, 70, 60, 30));
        lcdNumber_Func_LP_Ga_D0->setDigitCount(3);
        lcdNumber_Func_LP_Ga_D0->setProperty("value", QVariant(1.000000000000000));
        tabWidget_Func_LP->addTab(tab_Func_LP_Ga, QString());
        tabWidget_Func->addTab(tab_Func_LP, QString());
        tab_Func_HP = new QWidget();
        tab_Func_HP->setObjectName(QString::fromUtf8("tab_Func_HP"));
        tabWidget_Func_HP = new QTabWidget(tab_Func_HP);
        tabWidget_Func_HP->setObjectName(QString::fromUtf8("tabWidget_Func_HP"));
        tabWidget_Func_HP->setGeometry(QRect(10, 10, 325, 300));
        tab_Func_HP_ID = new QWidget();
        tab_Func_HP_ID->setObjectName(QString::fromUtf8("tab_Func_HP_ID"));
        groupBox_Func_HP_ID_D0 = new QGroupBox(tab_Func_HP_ID);
        groupBox_Func_HP_ID_D0->setObjectName(QString::fromUtf8("groupBox_Func_HP_ID_D0"));
        groupBox_Func_HP_ID_D0->setGeometry(QRect(10, 10, 300, 111));
        groupBox_Func_HP_ID_D0->setFont(font);
        horizontalSlider_Func_HP_ID_D0 = new QSlider(groupBox_Func_HP_ID_D0);
        horizontalSlider_Func_HP_ID_D0->setObjectName(QString::fromUtf8("horizontalSlider_Func_HP_ID_D0"));
        horizontalSlider_Func_HP_ID_D0->setGeometry(QRect(10, 30, 280, 50));
        horizontalSlider_Func_HP_ID_D0->setMinimum(1);
        horizontalSlider_Func_HP_ID_D0->setMaximum(500);
        horizontalSlider_Func_HP_ID_D0->setOrientation(Qt::Horizontal);
        lcdNumber_Func_HP_ID_D0 = new QLCDNumber(groupBox_Func_HP_ID_D0);
        lcdNumber_Func_HP_ID_D0->setObjectName(QString::fromUtf8("lcdNumber_Func_HP_ID_D0"));
        lcdNumber_Func_HP_ID_D0->setGeometry(QRect(230, 70, 60, 30));
        lcdNumber_Func_HP_ID_D0->setDigitCount(3);
        lcdNumber_Func_HP_ID_D0->setProperty("value", QVariant(1.000000000000000));
        tabWidget_Func_HP->addTab(tab_Func_HP_ID, QString());
        tab_Func_HP_Bu = new QWidget();
        tab_Func_HP_Bu->setObjectName(QString::fromUtf8("tab_Func_HP_Bu"));
        groupBox_Func_HP_Bu_D0 = new QGroupBox(tab_Func_HP_Bu);
        groupBox_Func_HP_Bu_D0->setObjectName(QString::fromUtf8("groupBox_Func_HP_Bu_D0"));
        groupBox_Func_HP_Bu_D0->setGeometry(QRect(10, 10, 300, 111));
        groupBox_Func_HP_Bu_D0->setFont(font);
        horizontalSlider_Func_HP_Bu_D0 = new QSlider(groupBox_Func_HP_Bu_D0);
        horizontalSlider_Func_HP_Bu_D0->setObjectName(QString::fromUtf8("horizontalSlider_Func_HP_Bu_D0"));
        horizontalSlider_Func_HP_Bu_D0->setGeometry(QRect(10, 30, 280, 50));
        horizontalSlider_Func_HP_Bu_D0->setMinimum(1);
        horizontalSlider_Func_HP_Bu_D0->setMaximum(500);
        horizontalSlider_Func_HP_Bu_D0->setOrientation(Qt::Horizontal);
        lcdNumber_Func_HP_Bu_D0 = new QLCDNumber(groupBox_Func_HP_Bu_D0);
        lcdNumber_Func_HP_Bu_D0->setObjectName(QString::fromUtf8("lcdNumber_Func_HP_Bu_D0"));
        lcdNumber_Func_HP_Bu_D0->setGeometry(QRect(230, 70, 60, 30));
        lcdNumber_Func_HP_Bu_D0->setDigitCount(3);
        lcdNumber_Func_HP_Bu_D0->setProperty("value", QVariant(1.000000000000000));
        groupBox_Func_HP_Bu_N = new QGroupBox(tab_Func_HP_Bu);
        groupBox_Func_HP_Bu_N->setObjectName(QString::fromUtf8("groupBox_Func_HP_Bu_N"));
        groupBox_Func_HP_Bu_N->setGeometry(QRect(10, 140, 300, 111));
        groupBox_Func_HP_Bu_N->setFont(font);
        horizontalSlider_Func_HP_Bu_N = new QSlider(groupBox_Func_HP_Bu_N);
        horizontalSlider_Func_HP_Bu_N->setObjectName(QString::fromUtf8("horizontalSlider_Func_HP_Bu_N"));
        horizontalSlider_Func_HP_Bu_N->setGeometry(QRect(10, 30, 280, 50));
        horizontalSlider_Func_HP_Bu_N->setMinimum(1);
        horizontalSlider_Func_HP_Bu_N->setMaximum(500);
        horizontalSlider_Func_HP_Bu_N->setPageStep(1);
        horizontalSlider_Func_HP_Bu_N->setOrientation(Qt::Horizontal);
        lcdNumber_Func_HP_Bu_N = new QLCDNumber(groupBox_Func_HP_Bu_N);
        lcdNumber_Func_HP_Bu_N->setObjectName(QString::fromUtf8("lcdNumber_Func_HP_Bu_N"));
        lcdNumber_Func_HP_Bu_N->setGeometry(QRect(230, 70, 60, 30));
        lcdNumber_Func_HP_Bu_N->setDigitCount(3);
        lcdNumber_Func_HP_Bu_N->setProperty("value", QVariant(1.000000000000000));
        tabWidget_Func_HP->addTab(tab_Func_HP_Bu, QString());
        tab_Func_HP_Ga = new QWidget();
        tab_Func_HP_Ga->setObjectName(QString::fromUtf8("tab_Func_HP_Ga"));
        groupBox_Func_HP_Ga_D0 = new QGroupBox(tab_Func_HP_Ga);
        groupBox_Func_HP_Ga_D0->setObjectName(QString::fromUtf8("groupBox_Func_HP_Ga_D0"));
        groupBox_Func_HP_Ga_D0->setGeometry(QRect(10, 10, 300, 111));
        groupBox_Func_HP_Ga_D0->setFont(font);
        horizontalSlider_Func_HP_Ga_D0 = new QSlider(groupBox_Func_HP_Ga_D0);
        horizontalSlider_Func_HP_Ga_D0->setObjectName(QString::fromUtf8("horizontalSlider_Func_HP_Ga_D0"));
        horizontalSlider_Func_HP_Ga_D0->setGeometry(QRect(10, 30, 280, 50));
        horizontalSlider_Func_HP_Ga_D0->setMinimum(1);
        horizontalSlider_Func_HP_Ga_D0->setMaximum(500);
        horizontalSlider_Func_HP_Ga_D0->setOrientation(Qt::Horizontal);
        lcdNumber_Func_HP_Ga_D0 = new QLCDNumber(groupBox_Func_HP_Ga_D0);
        lcdNumber_Func_HP_Ga_D0->setObjectName(QString::fromUtf8("lcdNumber_Func_HP_Ga_D0"));
        lcdNumber_Func_HP_Ga_D0->setGeometry(QRect(230, 70, 60, 30));
        lcdNumber_Func_HP_Ga_D0->setDigitCount(3);
        lcdNumber_Func_HP_Ga_D0->setProperty("value", QVariant(1.000000000000000));
        tabWidget_Func_HP->addTab(tab_Func_HP_Ga, QString());
        tabWidget_Func->addTab(tab_Func_HP, QString());
        tab_Func_Homo = new QWidget();
        tab_Func_Homo->setObjectName(QString::fromUtf8("tab_Func_Homo"));
        groupBox_Func_Homo_RH = new QGroupBox(tab_Func_Homo);
        groupBox_Func_Homo_RH->setObjectName(QString::fromUtf8("groupBox_Func_Homo_RH"));
        groupBox_Func_Homo_RH->setGeometry(QRect(20, 5, 300, 71));
        groupBox_Func_Homo_RH->setFont(font);
        horizontalSlider_Func_Homo_RH = new QSlider(groupBox_Func_Homo_RH);
        horizontalSlider_Func_Homo_RH->setObjectName(QString::fromUtf8("horizontalSlider_Func_Homo_RH"));
        horizontalSlider_Func_Homo_RH->setGeometry(QRect(10, 30, 211, 31));
        horizontalSlider_Func_Homo_RH->setMinimum(1);
        horizontalSlider_Func_Homo_RH->setMaximum(10);
        horizontalSlider_Func_Homo_RH->setValue(2);
        horizontalSlider_Func_Homo_RH->setOrientation(Qt::Horizontal);
        lcdNumber_Func_Homo_RH = new QLCDNumber(groupBox_Func_Homo_RH);
        lcdNumber_Func_Homo_RH->setObjectName(QString::fromUtf8("lcdNumber_Func_Homo_RH"));
        lcdNumber_Func_Homo_RH->setGeometry(QRect(230, 30, 60, 30));
        lcdNumber_Func_Homo_RH->setDigitCount(3);
        lcdNumber_Func_Homo_RH->setProperty("value", QVariant(2.000000000000000));
        lcdNumber_Func_Homo_RH->setProperty("intValue", QVariant(2));
        groupBox_Func_Homo_RL = new QGroupBox(tab_Func_Homo);
        groupBox_Func_Homo_RL->setObjectName(QString::fromUtf8("groupBox_Func_Homo_RL"));
        groupBox_Func_Homo_RL->setGeometry(QRect(20, 80, 300, 71));
        groupBox_Func_Homo_RL->setFont(font);
        horizontalSlider_Func_Homo_RL = new QSlider(groupBox_Func_Homo_RL);
        horizontalSlider_Func_Homo_RL->setObjectName(QString::fromUtf8("horizontalSlider_Func_Homo_RL"));
        horizontalSlider_Func_Homo_RL->setGeometry(QRect(10, 30, 211, 31));
        horizontalSlider_Func_Homo_RL->setMaximum(100);
        horizontalSlider_Func_Homo_RL->setValue(25);
        horizontalSlider_Func_Homo_RL->setOrientation(Qt::Horizontal);
        lcdNumber_Func_Homo_RL = new QLCDNumber(groupBox_Func_Homo_RL);
        lcdNumber_Func_Homo_RL->setObjectName(QString::fromUtf8("lcdNumber_Func_Homo_RL"));
        lcdNumber_Func_Homo_RL->setGeometry(QRect(230, 30, 60, 30));
        lcdNumber_Func_Homo_RL->setDigitCount(3);
        lcdNumber_Func_Homo_RL->setProperty("value", QVariant(25.000000000000000));
        groupBox_Func_Homo_C = new QGroupBox(tab_Func_Homo);
        groupBox_Func_Homo_C->setObjectName(QString::fromUtf8("groupBox_Func_Homo_C"));
        groupBox_Func_Homo_C->setGeometry(QRect(20, 150, 300, 71));
        groupBox_Func_Homo_C->setFont(font);
        horizontalSlider_Func_Homo_C = new QSlider(groupBox_Func_Homo_C);
        horizontalSlider_Func_Homo_C->setObjectName(QString::fromUtf8("horizontalSlider_Func_Homo_C"));
        horizontalSlider_Func_Homo_C->setGeometry(QRect(10, 30, 211, 31));
        horizontalSlider_Func_Homo_C->setMinimum(1);
        horizontalSlider_Func_Homo_C->setMaximum(10);
        horizontalSlider_Func_Homo_C->setOrientation(Qt::Horizontal);
        lcdNumber_Func_Homo_C = new QLCDNumber(groupBox_Func_Homo_C);
        lcdNumber_Func_Homo_C->setObjectName(QString::fromUtf8("lcdNumber_Func_Homo_C"));
        lcdNumber_Func_Homo_C->setGeometry(QRect(230, 30, 60, 30));
        lcdNumber_Func_Homo_C->setDigitCount(3);
        lcdNumber_Func_Homo_C->setProperty("value", QVariant(1.000000000000000));
        groupBox_Func_Homo_D0 = new QGroupBox(tab_Func_Homo);
        groupBox_Func_Homo_D0->setObjectName(QString::fromUtf8("groupBox_Func_Homo_D0"));
        groupBox_Func_Homo_D0->setGeometry(QRect(20, 220, 300, 71));
        groupBox_Func_Homo_D0->setFont(font);
        horizontalSlider_Func_Homo_D0 = new QSlider(groupBox_Func_Homo_D0);
        horizontalSlider_Func_Homo_D0->setObjectName(QString::fromUtf8("horizontalSlider_Func_Homo_D0"));
        horizontalSlider_Func_Homo_D0->setGeometry(QRect(10, 30, 211, 31));
        horizontalSlider_Func_Homo_D0->setMinimum(1);
        horizontalSlider_Func_Homo_D0->setMaximum(500);
        horizontalSlider_Func_Homo_D0->setValue(80);
        horizontalSlider_Func_Homo_D0->setOrientation(Qt::Horizontal);
        lcdNumber_Func_Homo_D0 = new QLCDNumber(groupBox_Func_Homo_D0);
        lcdNumber_Func_Homo_D0->setObjectName(QString::fromUtf8("lcdNumber_Func_Homo_D0"));
        lcdNumber_Func_Homo_D0->setGeometry(QRect(230, 30, 60, 30));
        lcdNumber_Func_Homo_D0->setDigitCount(3);
        lcdNumber_Func_Homo_D0->setProperty("value", QVariant(80.000000000000000));
        tabWidget_Func->addTab(tab_Func_Homo, QString());
        tab_Func_CreMBImg = new QWidget();
        tab_Func_CreMBImg->setObjectName(QString::fromUtf8("tab_Func_CreMBImg"));
        groupBox_Func_CreMBImg_A = new QGroupBox(tab_Func_CreMBImg);
        groupBox_Func_CreMBImg_A->setObjectName(QString::fromUtf8("groupBox_Func_CreMBImg_A"));
        groupBox_Func_CreMBImg_A->setGeometry(QRect(20, 10, 300, 101));
        groupBox_Func_CreMBImg_A->setFont(font);
        horizontalSlider_Func_CreMBImg_A = new QSlider(groupBox_Func_CreMBImg_A);
        horizontalSlider_Func_CreMBImg_A->setObjectName(QString::fromUtf8("horizontalSlider_Func_CreMBImg_A"));
        horizontalSlider_Func_CreMBImg_A->setGeometry(QRect(10, 30, 280, 31));
        horizontalSlider_Func_CreMBImg_A->setMaximum(100);
        horizontalSlider_Func_CreMBImg_A->setValue(8);
        horizontalSlider_Func_CreMBImg_A->setOrientation(Qt::Horizontal);
        lcdNumber_Func_CreMBImg_A = new QLCDNumber(groupBox_Func_CreMBImg_A);
        lcdNumber_Func_CreMBImg_A->setObjectName(QString::fromUtf8("lcdNumber_Func_CreMBImg_A"));
        lcdNumber_Func_CreMBImg_A->setGeometry(QRect(230, 60, 60, 30));
        lcdNumber_Func_CreMBImg_A->setDigitCount(3);
        lcdNumber_Func_CreMBImg_A->setProperty("value", QVariant(8.000000000000000));
        groupBox_Func_CreMBImg_B = new QGroupBox(tab_Func_CreMBImg);
        groupBox_Func_CreMBImg_B->setObjectName(QString::fromUtf8("groupBox_Func_CreMBImg_B"));
        groupBox_Func_CreMBImg_B->setGeometry(QRect(20, 120, 300, 101));
        groupBox_Func_CreMBImg_B->setFont(font);
        horizontalSlider_Func_CreMBImg_B = new QSlider(groupBox_Func_CreMBImg_B);
        horizontalSlider_Func_CreMBImg_B->setObjectName(QString::fromUtf8("horizontalSlider_Func_CreMBImg_B"));
        horizontalSlider_Func_CreMBImg_B->setGeometry(QRect(10, 30, 280, 31));
        horizontalSlider_Func_CreMBImg_B->setMaximum(100);
        horizontalSlider_Func_CreMBImg_B->setValue(8);
        horizontalSlider_Func_CreMBImg_B->setOrientation(Qt::Horizontal);
        lcdNumber_Func_CreMBImg_B = new QLCDNumber(groupBox_Func_CreMBImg_B);
        lcdNumber_Func_CreMBImg_B->setObjectName(QString::fromUtf8("lcdNumber_Func_CreMBImg_B"));
        lcdNumber_Func_CreMBImg_B->setGeometry(QRect(230, 60, 60, 30));
        lcdNumber_Func_CreMBImg_B->setDigitCount(3);
        lcdNumber_Func_CreMBImg_B->setProperty("value", QVariant(8.000000000000000));
        tabWidget_Func->addTab(tab_Func_CreMBImg, QString());
        tab_Func_RemMBImg = new QWidget();
        tab_Func_RemMBImg->setObjectName(QString::fromUtf8("tab_Func_RemMBImg"));
        tabWidget_Func_RemMBImg = new QTabWidget(tab_Func_RemMBImg);
        tabWidget_Func_RemMBImg->setObjectName(QString::fromUtf8("tabWidget_Func_RemMBImg"));
        tabWidget_Func_RemMBImg->setGeometry(QRect(10, 10, 321, 310));
        tab_Func_RemMBImg_IF = new QWidget();
        tab_Func_RemMBImg_IF->setObjectName(QString::fromUtf8("tab_Func_RemMBImg_IF"));
        groupBox_Func_RemMBImg_IF_A = new QGroupBox(tab_Func_RemMBImg_IF);
        groupBox_Func_RemMBImg_IF_A->setObjectName(QString::fromUtf8("groupBox_Func_RemMBImg_IF_A"));
        groupBox_Func_RemMBImg_IF_A->setGeometry(QRect(9, -1, 301, 91));
        groupBox_Func_RemMBImg_IF_A->setFont(font);
        horizontalSlider_Func_RemMBImg_IF_A = new QSlider(groupBox_Func_RemMBImg_IF_A);
        horizontalSlider_Func_RemMBImg_IF_A->setObjectName(QString::fromUtf8("horizontalSlider_Func_RemMBImg_IF_A"));
        horizontalSlider_Func_RemMBImg_IF_A->setGeometry(QRect(9, 30, 281, 21));
        horizontalSlider_Func_RemMBImg_IF_A->setMaximum(100);
        horizontalSlider_Func_RemMBImg_IF_A->setValue(8);
        horizontalSlider_Func_RemMBImg_IF_A->setOrientation(Qt::Horizontal);
        lcdNumber_Func_RemMBImg_IF_A = new QLCDNumber(groupBox_Func_RemMBImg_IF_A);
        lcdNumber_Func_RemMBImg_IF_A->setObjectName(QString::fromUtf8("lcdNumber_Func_RemMBImg_IF_A"));
        lcdNumber_Func_RemMBImg_IF_A->setGeometry(QRect(240, 50, 51, 31));
        lcdNumber_Func_RemMBImg_IF_A->setDigitCount(3);
        lcdNumber_Func_RemMBImg_IF_A->setProperty("value", QVariant(8.000000000000000));
        groupBox_Func_RemMBImg_IF_B = new QGroupBox(tab_Func_RemMBImg_IF);
        groupBox_Func_RemMBImg_IF_B->setObjectName(QString::fromUtf8("groupBox_Func_RemMBImg_IF_B"));
        groupBox_Func_RemMBImg_IF_B->setGeometry(QRect(10, 90, 301, 91));
        groupBox_Func_RemMBImg_IF_B->setFont(font);
        horizontalSlider_Func_RemMBImg_IF_B = new QSlider(groupBox_Func_RemMBImg_IF_B);
        horizontalSlider_Func_RemMBImg_IF_B->setObjectName(QString::fromUtf8("horizontalSlider_Func_RemMBImg_IF_B"));
        horizontalSlider_Func_RemMBImg_IF_B->setGeometry(QRect(9, 30, 281, 21));
        horizontalSlider_Func_RemMBImg_IF_B->setMaximum(100);
        horizontalSlider_Func_RemMBImg_IF_B->setValue(8);
        horizontalSlider_Func_RemMBImg_IF_B->setOrientation(Qt::Horizontal);
        lcdNumber_Func_RemMBImg_IF_B = new QLCDNumber(groupBox_Func_RemMBImg_IF_B);
        lcdNumber_Func_RemMBImg_IF_B->setObjectName(QString::fromUtf8("lcdNumber_Func_RemMBImg_IF_B"));
        lcdNumber_Func_RemMBImg_IF_B->setGeometry(QRect(240, 50, 51, 31));
        lcdNumber_Func_RemMBImg_IF_B->setDigitCount(3);
        lcdNumber_Func_RemMBImg_IF_B->setProperty("value", QVariant(8.000000000000000));
        tabWidget_Func_RemMBImg->addTab(tab_Func_RemMBImg_IF, QString());
        tab_Func_RemMBImg_WF = new QWidget();
        tab_Func_RemMBImg_WF->setObjectName(QString::fromUtf8("tab_Func_RemMBImg_WF"));
        groupBox_Func_RemMBImg_WF_A = new QGroupBox(tab_Func_RemMBImg_WF);
        groupBox_Func_RemMBImg_WF_A->setObjectName(QString::fromUtf8("groupBox_Func_RemMBImg_WF_A"));
        groupBox_Func_RemMBImg_WF_A->setGeometry(QRect(9, -1, 301, 91));
        groupBox_Func_RemMBImg_WF_A->setFont(font);
        horizontalSlider_Func_RemMBImg_WF_A = new QSlider(groupBox_Func_RemMBImg_WF_A);
        horizontalSlider_Func_RemMBImg_WF_A->setObjectName(QString::fromUtf8("horizontalSlider_Func_RemMBImg_WF_A"));
        horizontalSlider_Func_RemMBImg_WF_A->setGeometry(QRect(9, 30, 281, 21));
        horizontalSlider_Func_RemMBImg_WF_A->setMaximum(100);
        horizontalSlider_Func_RemMBImg_WF_A->setOrientation(Qt::Horizontal);
        lcdNumber_Func_RemMBImg_WF_A = new QLCDNumber(groupBox_Func_RemMBImg_WF_A);
        lcdNumber_Func_RemMBImg_WF_A->setObjectName(QString::fromUtf8("lcdNumber_Func_RemMBImg_WF_A"));
        lcdNumber_Func_RemMBImg_WF_A->setGeometry(QRect(240, 50, 51, 31));
        lcdNumber_Func_RemMBImg_WF_A->setDigitCount(3);
        groupBox_Func_RemMBImg_WF_B = new QGroupBox(tab_Func_RemMBImg_WF);
        groupBox_Func_RemMBImg_WF_B->setObjectName(QString::fromUtf8("groupBox_Func_RemMBImg_WF_B"));
        groupBox_Func_RemMBImg_WF_B->setGeometry(QRect(10, 90, 301, 91));
        groupBox_Func_RemMBImg_WF_B->setFont(font);
        horizontalSlider_Func_RemMBImg_WF_B = new QSlider(groupBox_Func_RemMBImg_WF_B);
        horizontalSlider_Func_RemMBImg_WF_B->setObjectName(QString::fromUtf8("horizontalSlider_Func_RemMBImg_WF_B"));
        horizontalSlider_Func_RemMBImg_WF_B->setGeometry(QRect(9, 30, 281, 21));
        horizontalSlider_Func_RemMBImg_WF_B->setMaximum(100);
        horizontalSlider_Func_RemMBImg_WF_B->setOrientation(Qt::Horizontal);
        lcdNumber_Func_RemMBImg_WF_B = new QLCDNumber(groupBox_Func_RemMBImg_WF_B);
        lcdNumber_Func_RemMBImg_WF_B->setObjectName(QString::fromUtf8("lcdNumber_Func_RemMBImg_WF_B"));
        lcdNumber_Func_RemMBImg_WF_B->setGeometry(QRect(240, 50, 51, 31));
        lcdNumber_Func_RemMBImg_WF_B->setDigitCount(3);
        groupBox_Func_RemMBImg_WF_K = new QGroupBox(tab_Func_RemMBImg_WF);
        groupBox_Func_RemMBImg_WF_K->setObjectName(QString::fromUtf8("groupBox_Func_RemMBImg_WF_K"));
        groupBox_Func_RemMBImg_WF_K->setGeometry(QRect(10, 180, 301, 91));
        groupBox_Func_RemMBImg_WF_K->setFont(font);
        horizontalSlider_Func_RemMBImg_WF_K = new QSlider(groupBox_Func_RemMBImg_WF_K);
        horizontalSlider_Func_RemMBImg_WF_K->setObjectName(QString::fromUtf8("horizontalSlider_Func_RemMBImg_WF_K"));
        horizontalSlider_Func_RemMBImg_WF_K->setGeometry(QRect(9, 30, 281, 21));
        horizontalSlider_Func_RemMBImg_WF_K->setMaximum(999);
        horizontalSlider_Func_RemMBImg_WF_K->setOrientation(Qt::Horizontal);
        lcdNumber_Func_RemMBImg_WF_K = new QLCDNumber(groupBox_Func_RemMBImg_WF_K);
        lcdNumber_Func_RemMBImg_WF_K->setObjectName(QString::fromUtf8("lcdNumber_Func_RemMBImg_WF_K"));
        lcdNumber_Func_RemMBImg_WF_K->setGeometry(QRect(240, 50, 51, 31));
        lcdNumber_Func_RemMBImg_WF_K->setDigitCount(3);
        tabWidget_Func_RemMBImg->addTab(tab_Func_RemMBImg_WF, QString());
        tabWidget_Func->addTab(tab_Func_RemMBImg, QString());
        pushButton_Execute = new QPushButton(groupBox_Func);
        pushButton_Execute->setObjectName(QString::fromUtf8("pushButton_Execute"));
        pushButton_Execute->setGeometry(QRect(10, 390, 350, 30));
        QFont font1;
        font1.setPointSize(16);
        font1.setBold(true);
        font1.setWeight(75);
        pushButton_Execute->setFont(font1);
        pushButton_Clear = new QPushButton(Widget);
        pushButton_Clear->setObjectName(QString::fromUtf8("pushButton_Clear"));
        pushButton_Clear->setGeometry(QRect(240, 20, 91, 30));

        retranslateUi(Widget);

        tabWidget_OriImgF->setCurrentIndex(0);
        tabWidget_ProImgF->setCurrentIndex(0);
        tabWidget_Func->setCurrentIndex(5);
        tabWidget_Func_LP->setCurrentIndex(2);
        tabWidget_Func_HP->setCurrentIndex(1);
        tabWidget_Func_RemMBImg->setCurrentIndex(1);


        QMetaObject::connectSlotsByName(Widget);
    } // setupUi

    void retranslateUi(QWidget *Widget)
    {
        Widget->setWindowTitle(QCoreApplication::translate("Widget", "hw3_mask", nullptr));
        pushButton_ChooseFolder->setText(QCoreApplication::translate("Widget", "Choose your image folder.", nullptr));
        groupBox_OriImg->setTitle(QCoreApplication::translate("Widget", "Original Image", nullptr));
        label_OriImg->setText(QString());
        label_ImageList->setText(QCoreApplication::translate("Widget", "Image list:", nullptr));
        groupBox_OriImgF->setTitle(QCoreApplication::translate("Widget", "Spectrum / Phase angle", nullptr));
        label_OriImgF_S->setText(QString());
        tabWidget_OriImgF->setTabText(tabWidget_OriImgF->indexOf(tab_OriImgF_S), QCoreApplication::translate("Widget", "Spectrum", nullptr));
        label_OriImgF_PA->setText(QString());
        tabWidget_OriImgF->setTabText(tabWidget_OriImgF->indexOf(tab_OriImgF_PA), QCoreApplication::translate("Widget", "Phase Angle", nullptr));
        groupBox_ProImg->setTitle(QCoreApplication::translate("Widget", "Processed Image", nullptr));
        label_ProImg->setText(QString());
        pushButton_ProImg_store->setText(QString());
        groupBox_ProImgF->setTitle(QCoreApplication::translate("Widget", "Spectrum / Phase angle", nullptr));
        label_ProImgF_S->setText(QString());
        tabWidget_ProImgF->setTabText(tabWidget_ProImgF->indexOf(tab_ProImgF_S), QCoreApplication::translate("Widget", "Spectrum", nullptr));
        label_ProImgF_PA->setText(QString());
        tabWidget_ProImgF->setTabText(tabWidget_ProImgF->indexOf(tab_ProImgF_PA), QCoreApplication::translate("Widget", "Phase Angle", nullptr));
        groupBox_Func->setTitle(QCoreApplication::translate("Widget", "Functions", nullptr));
        pushButton_IF->setText(QCoreApplication::translate("Widget", "Inverse Fourier", nullptr));
        pushButton_ADDN->setText(QCoreApplication::translate("Widget", "Add noise", nullptr));
        tabWidget_Func->setTabText(tabWidget_Func->indexOf(tab), QCoreApplication::translate("Widget", "Inverse Fourier / Add noise", nullptr));
        groupBox_Func_LP_ID_D0->setTitle(QCoreApplication::translate("Widget", "D0", nullptr));
        tabWidget_Func_LP->setTabText(tabWidget_Func_LP->indexOf(tab_Func_LP_ID), QCoreApplication::translate("Widget", "Ideal filter", nullptr));
        groupBox_Func_LP_Bu_D0->setTitle(QCoreApplication::translate("Widget", "D0", nullptr));
        groupBox_Func_LP_Bu_N->setTitle(QCoreApplication::translate("Widget", "n", nullptr));
        tabWidget_Func_LP->setTabText(tabWidget_Func_LP->indexOf(tab_Func_LP_Bu), QCoreApplication::translate("Widget", "Butterworth", nullptr));
        groupBox_Func_LP_Ga_D0->setTitle(QCoreApplication::translate("Widget", "D0", nullptr));
        tabWidget_Func_LP->setTabText(tabWidget_Func_LP->indexOf(tab_Func_LP_Ga), QCoreApplication::translate("Widget", "Gaussion", nullptr));
        tabWidget_Func->setTabText(tabWidget_Func->indexOf(tab_Func_LP), QCoreApplication::translate("Widget", "LowPass", nullptr));
        groupBox_Func_HP_ID_D0->setTitle(QCoreApplication::translate("Widget", "D0", nullptr));
        tabWidget_Func_HP->setTabText(tabWidget_Func_HP->indexOf(tab_Func_HP_ID), QCoreApplication::translate("Widget", "Ideal filter", nullptr));
        groupBox_Func_HP_Bu_D0->setTitle(QCoreApplication::translate("Widget", "D0", nullptr));
        groupBox_Func_HP_Bu_N->setTitle(QCoreApplication::translate("Widget", "n", nullptr));
        tabWidget_Func_HP->setTabText(tabWidget_Func_HP->indexOf(tab_Func_HP_Bu), QCoreApplication::translate("Widget", "Butterworth", nullptr));
        groupBox_Func_HP_Ga_D0->setTitle(QCoreApplication::translate("Widget", "D0", nullptr));
        tabWidget_Func_HP->setTabText(tabWidget_Func_HP->indexOf(tab_Func_HP_Ga), QCoreApplication::translate("Widget", "Gaussion", nullptr));
        tabWidget_Func->setTabText(tabWidget_Func->indexOf(tab_Func_HP), QCoreApplication::translate("Widget", "HighPass", nullptr));
        groupBox_Func_Homo_RH->setTitle(QCoreApplication::translate("Widget", "\316\263_H", nullptr));
        groupBox_Func_Homo_RL->setTitle(QCoreApplication::translate("Widget", "\316\263_L * 100", nullptr));
        groupBox_Func_Homo_C->setTitle(QCoreApplication::translate("Widget", "c", nullptr));
        groupBox_Func_Homo_D0->setTitle(QCoreApplication::translate("Widget", "D0", nullptr));
        tabWidget_Func->setTabText(tabWidget_Func->indexOf(tab_Func_Homo), QCoreApplication::translate("Widget", "Homomorphic", nullptr));
        groupBox_Func_CreMBImg_A->setTitle(QCoreApplication::translate("Widget", "a*100", nullptr));
        groupBox_Func_CreMBImg_B->setTitle(QCoreApplication::translate("Widget", "b*100", nullptr));
        tabWidget_Func->setTabText(tabWidget_Func->indexOf(tab_Func_CreMBImg), QCoreApplication::translate("Widget", "Create motion blurred", nullptr));
        groupBox_Func_RemMBImg_IF_A->setTitle(QCoreApplication::translate("Widget", "a*100", nullptr));
        groupBox_Func_RemMBImg_IF_B->setTitle(QCoreApplication::translate("Widget", "b*100", nullptr));
        tabWidget_Func_RemMBImg->setTabText(tabWidget_Func_RemMBImg->indexOf(tab_Func_RemMBImg_IF), QCoreApplication::translate("Widget", "Inverse filter", nullptr));
        groupBox_Func_RemMBImg_WF_A->setTitle(QCoreApplication::translate("Widget", "a", nullptr));
        groupBox_Func_RemMBImg_WF_B->setTitle(QCoreApplication::translate("Widget", "b", nullptr));
        groupBox_Func_RemMBImg_WF_K->setTitle(QCoreApplication::translate("Widget", "K", nullptr));
        tabWidget_Func_RemMBImg->setTabText(tabWidget_Func_RemMBImg->indexOf(tab_Func_RemMBImg_WF), QCoreApplication::translate("Widget", "Wiener filter", nullptr));
        tabWidget_Func->setTabText(tabWidget_Func->indexOf(tab_Func_RemMBImg), QCoreApplication::translate("Widget", "Remove Motion Blurred", nullptr));
        pushButton_Execute->setText(QCoreApplication::translate("Widget", "Execute", nullptr));
        pushButton_Clear->setText(QCoreApplication::translate("Widget", "Clear", nullptr));
    } // retranslateUi

};

namespace Ui {
    class Widget: public Ui_Widget {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_WIDGET_H
